// Simulated Agent Memory / Database
// CLEARED FOR LIVE MODE
const AGENT_DATA = {
    market: {
        spx: 0,
        vix: 0,
        iv_rank: 0,
        mmm: 0,
        trend: "Waiting...",
        regime: "Initializing..."
    },
    forecast: {
        direction: "Neutral",
        probability: 0,
        skew_recommendation: "Waiting for Data...",
        conviction_summary: "Scanning Markets...",
        conviction_full_report: "Waiting for Live Bridge Connection..."
    },
    active_trade: null, // No trade until generated by live data
    chat_history: [
        { sender: "agent", text: "Alpha Intelligence System Initializing..." },
        { sender: "agent", text: "Connecting to Python Data Bridge for Real-Time Feeds..." }
    ]
};
